# railway.toml


[build]
dockerfile = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:5000 --workers 4 main:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"


[env]
FLASK_APP = "app.py"
FLASK_ENV = "production"
